services:
  # Judge0 API Service
  - type: web
    name: judge0-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: judge0-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: judge0-redis
          property: connectionString
      - key: PORT
        value: 2358

  # Judge0 Worker Service
  - type: worker
    name: judge0-worker
    env: docker
    dockerfilePath: ./worker/Dockerfile
    dockerContext: ./worker
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: judge0-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: judge0-redis
          property: connectionString
      - key: PORT
        value: 2358

databases:
  - name: judge0-db
    plan: starter
    region: oregon

  - name: judge0-redis
    type: keyvalue
    plan: starter
    region: oregon
