source 'https://rubygems.org'

ruby '3.0.6'

gem 'rails', '~> 6.0.0'
gem 'puma', '~> 5.0'
gem 'pg', '~> 1.1'
gem 'redis', '~> 4.0'
gem 'sidekiq', '~> 6.0'
gem 'rack-cors'
gem 'json'
gem 'bootsnap', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end
