# Render configuration for Judge0 API service
services:
  - type: web
    name: judge0-api-full
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: 2358
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: judge0-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: judge0-redis
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true