# Render configuration for Judge0 API service
# Based on official Judge0 repository structure
services:
  - type: web
    name: judge0-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard # Optimized for 200-300 students
    region: oregon
    envVars:
      # Rails Configuration
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: PORT
        value: 2358
      - key: SECRET_KEY_BASE
        generateValue: true
      
      # PostgreSQL Configuration (from database service)
      - key: POSTGRES_HOST
        fromDatabase:
          name: judge0-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: judge0-db
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: judge0-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: judge0-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: judge0-db
          property: password
      
      # Redis Configuration (from redis service)
      - key: REDIS_HOST
        fromService:
          type: redis
          name: judge0-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: judge0-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: judge0-redis
          property: password
      - key: REDIS_URL
        fromService:
          type: redis
          name: judge0-redis
          property: connectionString
      
      # Direct Redis URL override (forces connection to Render Redis)
      - key: REDIS_URL_OVERRIDE
        value: "redis://red-d3h1lch5pdvs73essm20:6379"
      
      # Additional Redis Configuration for Judge0
      - key: REDIS_DB
        value: "0"
      - key: REDIS_NAMESPACE
        value: "resque:"
      
      # Judge0 Configuration
      - key: JUDGE0_VERSION
        value: "1.13.1"
      
      # Judge0 Server Configuration
      - key: JUDGE0_TELEMETRY_ENABLE
        value: "false"
      - key: RESTART_MAX_TRIES
        value: "10"
      - key: MAINTENANCE_MODE
        value: "false"
      - key: ENABLE_WAIT_RESULT
        value: "true"
      - key: ENABLE_COMPILER_OPTIONS
        value: "true"
      - key: ENABLE_COMMAND_LINE_ARGUMENTS
        value: "true"
      - key: ENABLE_SUBMISSION_DELETE
        value: "false"
      - key: ENABLE_BATCHED_SUBMISSIONS
        value: "true"
      - key: MAX_SUBMISSION_BATCH_SIZE
        value: "20"
      - key: ENABLE_CALLBACKS
        value: "true"
      - key: CALLBACKS_MAX_TRIES
        value: "3"
      - key: CALLBACKS_TIMEOUT
        value: "5"
      - key: ENABLE_ADDITIONAL_FILES
        value: "true"
      - key: SUBMISSION_CACHE_DURATION
        value: "1"
      - key: USE_DOCS_AS_HOMEPAGE
        value: "false"
      - key: DISABLE_IMPLICIT_BASE64_ENCODING
        value: "false"
      
      # Judge0 Workers Configuration (Optimized for 200-300 students)
      - key: INTERVAL
        value: "0.1"
      - key: COUNT
        value: "3"
      - key: MAX_QUEUE_SIZE
        value: "100"
      
      # Submission Configuration
      - key: CPU_TIME_LIMIT
        value: "5"
      - key: MAX_CPU_TIME_LIMIT
        value: "15"
      - key: CPU_EXTRA_TIME
        value: "2"
      - key: MAX_CPU_EXTRA_TIME
        value: "5"
      - key: WALL_TIME_LIMIT
        value: "10"
      - key: MAX_WALL_TIME_LIMIT
        value: "20"
      - key: MEMORY_LIMIT
        value: "128000"
      - key: MAX_MEMORY_LIMIT
        value: "512000"
      - key: STACK_LIMIT
        value: "128000"
      - key: MAX_STACK_LIMIT
        value: "256000"
      - key: MAX_PROCESSES_AND_OR_THREADS
        value: "60"
      - key: MAX_MAX_PROCESSES_AND_OR_THREADS
        value: "120"
      - key: ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT
        value: "false"
      - key: ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT
        value: "true"
      - key: ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT
        value: "false"
      - key: ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT
        value: "true"
      - key: MAX_FILE_SIZE
        value: "1024"
      - key: MAX_MAX_FILE_SIZE
        value: "4096"
      - key: NUMBER_OF_RUNS
        value: "1"
      - key: MAX_NUMBER_OF_RUNS
        value: "20"
      - key: REDIRECT_STDERR_TO_STDOUT
        value: "false"
      - key: MAX_EXTRACT_SIZE
        value: "10240"
      - key: ALLOW_ENABLE_NETWORK
        value: "true"
      - key: ENABLE_NETWORK
        value: "false"
      
      # Rails Configuration (Optimized for 200-300 students)
      - key: RAILS_MAX_THREADS
        value: "8"
      - key: RAILS_SERVER_PROCESSES
        value: "2"
      - key: DATABASE_POOL
        value: "25"
      
      # Resque Redis Configuration (Judge0 uses these specific variables)
      - key: RESQUE_REDIS
        value: "redis://red-d3h1lch5pdvs73essm20:6379"
      - key: RESQUE_REDIS_SCHEDULER
        value: "redis://red-d3h1lch5pdvs73essm20:6379"
      
      # Alternative Redis connection methods
      - key: REDIS_URL_RESQUE
        value: "redis://red-d3h1lch5pdvs73essm20:6379"
      - key: REDIS_URL_RESQUE_SCHEDULER
        value: "redis://red-d3h1lch5pdvs73essm20:6379"
      
      # Additional Redis Configuration (Force Judge0 to use Render Redis)
      - key: REDIS_HOST
        value: "red-d3h1lch5pdvs73essm20"
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_DB
        value: "0"
      - key: REDIS_PASSWORD
        value: ""
      - key: REDIS_NAMESPACE
        value: "judge0"
      - key: REDIS_SIDEKIQ_URL
        value: "redis://red-d3h1lch5pdvs73essm20:6379"