services:
  - type: worker
    name: judge0-worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: judge0-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: judge0-redis
          property: connectionString
      - key: PORT
        value: 2358

databases:
  - name: judge0-db
    plan: starter
    region: oregon

  - name: judge0-redis
    type: keyvalue
    plan: starter
    region: oregon
