# Render configuration for Judge0 Worker service
services:
  - type: worker
    name: judge0-worker-full
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: judge0-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: judge0-redis
          property: connectionString