# Render configuration for Judge0 Worker service
# Based on official Judge0 repository structure
services:
  - type: worker
    name: judge0-worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      # Rails Configuration
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      
      # PostgreSQL Configuration (from database service)
      - key: POSTGRES_HOST
        fromDatabase:
          name: judge0-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: judge0-db
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: judge0-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: judge0-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: judge0-db
          property: password
      
      # Redis Configuration (from redis service)
      - key: REDIS_HOST
        fromService:
          type: redis
          name: judge0-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: judge0-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: judge0-redis
          property: password
      
      # Judge0 Configuration
      - key: JUDGE0_VERSION
        value: "1.13.1"